### ISSUE TITLE
Specify domain or IP address?

### ISSUE THREAD

**Issue by mbriney** [pwt/docker-sonos-web-arm#3]
Is there a way to specify a domain or IP address?  When I try and connect Spotify it goes through the oAuth but then tries to redirect back to localhost.  But I'm accessing it off a non-local IP address and don't have a GUI setup on my Pi.

**Comment by pwt** [comment]
Hi @mbriney: I think it's best if you raise this question on the Sonos Web project itself: https://github.com/Villarrealized/sonos-web/issues.

I just provide the Docker packaging, and I have very limited expertise in Sonos Web itself. The Docker image should behave identically to the non-Docker version from a network perspective, however.

**Comment by pwt** [comment]
It appears from https://github.com/Villarrealized/sonos-web/issues/36 that the workaround to this doesn't require any changes to the Docker packaging or documentation, so I'll close this issue.
