### ISSUE TITLE
Build breaks with failed front-end dependencies

### ISSUE THREAD

**Issue by garethhumphriesgkc** [pwt/docker-sonos-web-arm#4]
✔ downloading installation files
✖ installing front-end dependencies
error installation failed...check /root/.sonos-web/install.log for more details

Log file is zero-bytes.

**Comment by pwt** [comment]
Sonos-web has essentially been dormant for 18 months, and I know there has been a succession of build issues. Hence I haven't been maintaining this Docker ARM build.

The existing Docker image on DockerHub should still run, however.
