### ISSUE TITLE
Docker Hub says the "latest" tagged image is built for linux/amd64 instead of linux/arm/v7

### ISSUE THREAD

**Issue by jimaldon** [pwt/docker-sonos-web-arm#5]
https://hub.docker.com/r/psychlist/docker-sonos-web-arm/tags

**Comment by pwt** [comment]
You're right, even though the image is definitely an ARM one.

This image was built by DockerHub, back in the days when builds were part of the free offering. The build uses the Balena cross-build feature, to create an ARM image on an amd64 host.

As Sonos-Web appears to be a dead project, I'm not planning to update the image, and I'll retire this repo.
